---
# =====================================================
# Control Node
# =====================================================
- name: "[ Setup Control Node.. ]"
  hosts: localhost
  become: true
  gather_facts: false

  roles:
#    - control

# =====================================================
# Ubuntu Servers
# =====================================================
- name: "[ Ubuntu_Servers Settings.. ]"
  hosts: Ubuntu_Servers
  become: true
  gather_facts: false

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
#    - root_password
#    - packages
#    - pip_packages
#    - nicname
#    - cloud_init
#    - ufw
#    - locale_ko
#    - ssh_root_login
#    - timezone
#    - ntp
#    - open_files
#    - logrotate
#    - shell_default
#    - node_export
#    - java
#    - disable_swap
#    - package_version_lock
#    - package_update_lock
#    - bash_common
#    - ssh_keygen
#    - etc_hosts

# =====================================================
# Docker Servers
# =====================================================
- name: "[ Docker_Servers Settings.. ]"
  hosts: Docker_Servers
  become: true
  gather_facts: true

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
#    - docker

# =====================================================
# Zookeeper Servers
# =====================================================
- name: "[ Zookeeper_Servers Settings.. ]"
  hosts: Zookeeper_Servers
  become: true
  gather_facts: false

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
#    - zookeeper

# =====================================================
# Kafka Servers
# =====================================================
- name: "[ Kafka_Servers Settings.. ]"
  hosts: Kafka_Servers
  become: true
  gather_facts: false

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
#    - kafka

# =====================================================
# Hadoop Servers
# =====================================================
- name: "[ Hadoop_Servers Settings.. ]"
  hosts: Hadoop_Servers
  become: true
  gather_facts: false

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
#    - hadoop

# =====================================================
# Elasticsearch Servers
# =====================================================
- name: "[ Elasticsearch_Servers Settings.. ]"
  hosts: Elasticsearch_Servers
  become: true
  gather_facts: false

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
#    - elasticsearch

# =====================================================
# Kibana Servers
# =====================================================
- name: "[ Kibana_Servers Settings.. ]"
  hosts: Kibana_Servers
  become: true
  gather_facts: false

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
    - kibana

# =====================================================
# Redis Servers
# =====================================================
- name: "[ Redis_Servers Settings.. ]"
  hosts: Redis_Servers
  become: true
  gather_facts: false

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
#    - redis

# =====================================================
# PostgreSQL Servers
# =====================================================
- name: "[ PostgreSQL_Servers Settings ]"
  hosts: PostgreSQL_Servers
  become: true
  gather_facts: false

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
#    - postgresql
